name: Deploy

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set a Node.js version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # pull code
      - name: Checkout code
        uses: actions/checkout@v3

      # install deps
      - run: npm i -g pnpm

      - run: pnpm install

      - run: pnpm build:example

      # deploy to github pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: example
          silent: true
          clean: true
          branch: gh-pages
          single-commit: true